export class Programme4 {
    programme4:any;
    annee:any;
    site:any;
    commun:any;
    douar:any;
    proact:any;
    intitule:any;
    sousprojet:any;
    typeprojet:any;
    natureinterv:any;
    qte:any;
    cout:any;
    demcible:any;
    probcible:any;
    freindev:any;
    qtetotal:any;
    partindh:any;
    delai:any;
    ntrben:any;
    nbrben:any;
    partenir_id:any;
    validation:any;
}
